### PR TITLE
Made some improvements and fixed bugs

### PR DESCRIPTION
**Pull request by Flushot**
Hey, nice and useful project!

Not sure if it's still being maintained, but I've made a few changes to the code, if you'd like to add them:

- Progress bar is updated on a polling timer instead of an event, so that speed is improved
- Wordlist offset in config is working now
- Fixed bug: "Use keyfiles" config option was saving, but not loading
- Added a lineCount param to WordListPasswordProvider.LoadWordList() so that analysis phase can be skipped
- When thread exits with exception, it will be logged and all threads will stop
- Added "show password" checkbox to prevent exposure of cracked passwords to anyone looking at monitor
- Made log and cracked password textbox read-only
- Fixed bug: Key files weren't being applied to passwords
- Fixed bug: Key files dialog would get out of sync with config when switching
- Fixed bug: Exceptions raised during save would cause the configuration to be lost

### CODE REVIEW

**Comment by IsNull** [comment]
Now this is unexpected! Thanks for your great contributions, I gladly will merge those in once you think its ready.

If I remember correctly, there was an issue with the keyfiles. Mixing the keyfiles into the password buffer was not working properly, thus the `NotImplementedException`.

**Comment by Flushot** [comment]
Hmm, I tested it with 1 keyfile and it seemed to work. Seemed to break when I used 2 keyfiles though.

When I compared it with TrueCrypt's KeyFilesApply() function, I noticed crc and writePos were supposed to be reset between loading keyfiles. Fixed in commit https://github.com/IsNull/TCBrute/pull/7/commits/6edeb606cc1ea8bb1d80e0af91819ce313c9a16e

**Comment by IsNull** [comment]
Yes the missing resetting would explain why it didn't work with more than one keyfile. 

Let me know when you want to merge 👍

**Comment by Flushot** [comment]
Hey, I've made my last bit of changes. Fixed a few other bugs.
Merge away!

**Pull request merged**
